name: surf_practice_magic_ball
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.0.3
  flutter: ^3.10.3

dependencies:
  dio: ^5.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  fpdart: ^0.6.0
  freezed_annotation: ^2.4.1
  material_design_icons_flutter: ^7.0.7296
  morphable_shape: ^1.6.6
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.1.5
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  lint: ^2.1.2

flutter:
  uses-material-design: true
